---
categories:
  - alignment
  - backgrounds
  - bgcolor
  - border
  - effects
  - flexbox
  - grid
  - interactivity
  - layout
  - sizing
  - spacing
  - tables
  - typography
screens:
  xs:
    min: 0px
    max: 639px
  sm:
    min: 640px
    max: 767px
  md:
    min: 768px
    max: 1023px
  lg:
    min: 1024px
    max: 2000px
states:
  - link
  - visited
  - hover
  - focus
  - active
  - checked
  - disabled  
  - focus-visible  
  - required  